### ISSUE TITLE
Proposal to rename `src/` to something else

### ISSUE THREAD

**Issue by BoringDonut** [ashuramaruzxc/anime-cursors#6]
It would be nice to have a module name. So project can be imported/executed by a meaningful name, or packaged to `.whl` in the future
Consider something like `CursorConvertor/`
You might use https://pypi.org/ to check if name is already used by someone

**Comment by ashuramaruzxc** [comment]
[61f573c](https://github.com/ashuramaruzxc/anime-cursors/commit/61f573c65ac2fa1bae673de189c627a39b3e0541) Fixes the issue
